"""make invoices appointment_id and user_id nullable for fleet invoices

Revision ID: 1b9b9e2ac618
Revises: fd2f12efb061
Create Date: 2026-08-27 07:00:44.098416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9b9e2ac618'
down_revision = 'fd2f12efb061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('appointment_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
