"""add_documents_signatures_audit_tables

Revision ID: 519a14b69d0d
Revises: 7a8b9c0d1e2f
Create Date: 2026-09-16 23:45:31.774552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519a14b69d0d'
down_revision = '7a8b9c0d1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_status_date', ['status', 'appointment_date'], unique=False)
        batch_op.create_index('ix_appointments_user_payment', ['user_id', 'payment_status'], unique=False)
        batch_op.create_index('ix_appointments_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documents_doc_type_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('documents_status_check'), type_='check')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_appointment_status', ['appointment_id', 'status'], unique=False)
        batch_op.create_index('ix_invoices_company_status', ['company_id', 'status'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_invoice_status', ['invoice_id', 'status'], unique=False)
        batch_op.create_index('ix_payments_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('proof_of_work_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proof_of_work_media_media_type_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('proof_of_work_media_mime_type_check'), type_='check')

    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('signatures_status_check'), type_='check')

    with op.batch_alter_table('vehicle_checklists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vehicle_checklists_assignment_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_vehicle_checklists_assignment_id'))
        batch_op.create_index(batch_op.f('ix_vehicle_checklists_assignment_id'), ['assignment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicle_checklists_overall_condition'), ['overall_condition'], unique=False)
        batch_op.drop_constraint(batch_op.f('vehicle_checklists_overall_condition_check'), type_='check')

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('webhook_events_source_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('webhook_events_status_check'), type_='check')

    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('work_records_assignment_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_work_records_assignment_id'))
        batch_op.create_index(batch_op.f('ix_work_records_assignment_id'), ['assignment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_records_verified_by'), ['verified_by'], unique=False)
        batch_op.drop_constraint(batch_op.f('work_records_status_check'), type_='check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('work_records_status_check'), "status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'verified'::character varying, 'invoiced'::character varying]::text[])")
        batch_op.drop_index(batch_op.f('ix_work_records_verified_by'))
        batch_op.drop_index(batch_op.f('ix_work_records_assignment_id'))
        batch_op.create_index(batch_op.f('ix_work_records_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('work_records_assignment_id_key'), ['assignment_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('webhook_events_status_check'), "status::text = ANY (ARRAY['unprocessed'::character varying, 'processing'::character varying, 'processed'::character varying, 'failed'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('webhook_events_source_check'), "source::text = ANY (ARRAY['mpesa'::character varying, 'card'::character varying, 'bank_transfer'::character varying, 'other'::character varying]::text[])")

    with op.batch_alter_table('vehicle_checklists', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('vehicle_checklists_overall_condition_check'), "overall_condition::text = ANY (ARRAY['excellent'::character varying, 'good'::character varying, 'fair'::character varying, 'poor'::character varying]::text[])")
        batch_op.drop_index(batch_op.f('ix_vehicle_checklists_overall_condition'))
        batch_op.drop_index(batch_op.f('ix_vehicle_checklists_assignment_id'))
        batch_op.create_index(batch_op.f('ix_vehicle_checklists_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('vehicle_checklists_assignment_id_key'), ['assignment_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('signatures_status_check'), "status::text = ANY (ARRAY['pending'::character varying, 'captured'::character varying, 'verified'::character varying, 'rejected'::character varying]::text[])")

    with op.batch_alter_table('proof_of_work_media', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('proof_of_work_media_mime_type_check'), "mime_type::text = ANY (ARRAY['image/jpeg'::character varying, 'image/png'::character varying, 'image/webp'::character varying, 'image/gif'::character varying, 'image/heic'::character varying, 'image/heif'::character varying, 'video/mp4'::character varying, 'video/webm'::character varying, 'video/quicktime'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('proof_of_work_media_media_type_check'), "media_type::text = ANY (ARRAY['image'::character varying, 'video'::character varying]::text[])")

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_user_status')
        batch_op.drop_index('ix_payments_invoice_status')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_company_status')
        batch_op.drop_index('ix_invoices_appointment_status')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('documents_status_check'), "status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'signed'::character varying, 'declined'::character varying, 'cancelled'::character varying, 'expired'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('documents_doc_type_check'), "doc_type::text = ANY (ARRAY['work_order'::character varying, 'service_agreement'::character varying, 'invoice'::character varying, 'other'::character varying]::text[])")

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_user_status')
        batch_op.drop_index('ix_appointments_user_payment')
        batch_op.drop_index('ix_appointments_status_date')

    # ### end Alembic commands ###
