"""add_phone_search_token_to_user

Revision ID: 7e8cc92731ff
Revises: 600e7d28cbcb
Create Date: 2026-09-02 16:09:19.655529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8cc92731ff'
down_revision = '600e7d28cbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_search_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone_search_token'), ['phone_search_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_search_token'))
        batch_op.drop_column('phone_search_token')

    # ### end Alembic commands ###
