"""increase phone column length

Revision ID: fd2f12efb061
Revises: c128faab65cb
Create Date: 2026-08-27 05:57:54.676317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.core.types import EncryptedString

# revision identifiers, used by Alembic.
revision = 'fd2f12efb061'
down_revision = 'c128faab65cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_created_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_date_idx'))
        batch_op.drop_index(batch_op.f('ix_appointments_status_date_idx'))
        batch_op.drop_index(batch_op.f('ix_appointments_status_idx'))
        batch_op.drop_index(batch_op.f('ix_appointments_user_date_idx'))
        batch_op.drop_index(batch_op.f('ix_appointments_user_status'))
        batch_op.create_index(batch_op.f('ix_appointments_overdue_notified'), ['overdue_notified'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_reminder_sent'), ['reminder_sent'], unique=False)
        batch_op.drop_constraint(batch_op.f('appointments_status_check'), type_='check')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('assignments_status_check'), type_='check')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_logs_status_check'), type_='check')

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_codes_active'))
        batch_op.drop_index(batch_op.f('ix_discount_codes_code_idx'))
        batch_op.drop_index(batch_op.f('ix_discount_codes_expiry'))

    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employee_documents_doc_type_check'), type_='check')

    with op.batch_alter_table('employee_time_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employee_time_logs_action_check'), type_='check')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_created_at'))
        batch_op.drop_index(batch_op.f('ix_employees_rating'))
        batch_op.drop_index(batch_op.f('ix_employees_specialties_gin'), postgresql_using='gin')
        batch_op.drop_constraint(batch_op.f('chk_employee_rating'), type_='check')
        batch_op.drop_constraint(batch_op.f('employees_account_status_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('employees_employment_type_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('employees_rating_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('employees_status_check'), type_='check')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('invoice_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))
        batch_op.create_index(batch_op.f('ix_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(batch_op.f('invoices_status_check'), type_='check')

    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('issue_reports_priority_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('issue_reports_status_check'), type_='check')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.alter_column('cardholder_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_method_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('payments_status_check'), type_='check')

    with op.batch_alter_table('service_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('service_history_rating_check'), type_='check')

    with op.batch_alter_table('service_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_partners_address_gin'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_service_partners_rating'))
        batch_op.drop_index(batch_op.f('ix_service_partners_services_gin'), postgresql_using='gin')
        batch_op.drop_constraint(batch_op.f('service_partners_rating_check'), type_='check')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_created_at'))
        batch_op.drop_index(batch_op.f('ix_services_price'))
        batch_op.drop_index(batch_op.f('ix_services_search'), postgresql_using='gin')
        batch_op.drop_constraint(batch_op.f('chk_service_duration'), type_='check')
        batch_op.drop_constraint(batch_op.f('chk_service_price'), type_='check')
        batch_op.drop_column('search_vector')

    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_metrics_metric_name'))

    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('time_off_requests_request_type_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('time_off_requests_status_check'), type_='check')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_token_blocklist_expires_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=EncryptedString(length=255),
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_name_gin'), postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_constraint(batch_op.f('chk_user_role'), type_='check')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_created_at'))
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_make_model'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_make_model'), ['make', 'model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('chk_user_role'), "role::text = ANY (ARRAY['admin'::character varying, 'employee'::character varying, 'customer'::character varying]::text[])")
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name_gin'), ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('phone',
               existing_type=EncryptedString(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('time_off_requests', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('time_off_requests_status_check'), "status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('time_off_requests_request_type_check'), "request_type::text = ANY (ARRAY['vacation'::character varying, 'sick'::character varying, 'personal'::character varying, 'other'::character varying]::text[])")

    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_metrics_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_check_constraint(batch_op.f('chk_service_price'), 'price >= 0::numeric')
        batch_op.create_check_constraint(batch_op.f('chk_service_duration'), 'duration > 0')
        batch_op.create_index(batch_op.f('ix_services_search'), [sa.literal_column("to_tsvector('english'::regconfig, (name::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_services_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('service_partners', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('service_partners_rating_check'), 'rating >= 0.00 AND rating <= 5.00')
        batch_op.create_index(batch_op.f('ix_service_partners_services_gin'), ['services_offered'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_service_partners_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_partners_address_gin'), ['address'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('service_history', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('service_history_rating_check'), 'rating >= 0 AND rating <= 5')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('payments_status_check'), "status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('payments_method_check'), "method::text = ANY (ARRAY['mpesa'::character varying, 'card'::character varying, 'cash'::character varying, 'bank_transfer'::character varying]::text[])")

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('cardholder_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('issue_reports', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('issue_reports_status_check'), "status::text = ANY (ARRAY['open'::character varying, 'in-progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('issue_reports_priority_check'), "priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])")

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('invoices_status_check'), "status::text = ANY (ARRAY['draft'::character varying, 'sent'::character varying, 'paid'::character varying, 'void'::character varying]::text[])")
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_company_id'))
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('due_date')
        batch_op.drop_column('currency')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('invoice_type')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.create_check_constraint(batch_op.f('employees_status_check'), "status::text = ANY (ARRAY['active'::character varying, 'off-duty'::character varying, 'suspended'::character varying, 'terminated'::character varying, 'pending'::character varying, 'rejected'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('employees_rating_check'), 'rating >= 0.00 AND rating <= 5.00')
        batch_op.create_check_constraint(batch_op.f('employees_employment_type_check'), "employment_type::text = ANY (ARRAY['full_time'::character varying, 'part_time'::character varying, 'contractor'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('employees_account_status_check'), "account_status::text = ANY (ARRAY['active'::character varying, 'onboarding'::character varying, 'suspended'::character varying, 'terminated'::character varying]::text[])")
        batch_op.create_check_constraint(batch_op.f('chk_employee_rating'), 'rating >= 0::numeric AND rating <= 5::numeric')
        batch_op.create_index(batch_op.f('ix_employees_specialties_gin'), ['specialties'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_employees_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('employee_time_logs', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('employee_time_logs_action_check'), "action::text = ANY (ARRAY['in'::character varying, 'out'::character varying]::text[])")

    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('employee_documents_doc_type_check'), "doc_type::text = ANY (ARRAY['id_proof'::character varying, 'tax_form'::character varying, 'certification'::character varying, 'contract'::character varying, 'other'::character varying]::text[])")

    with op.batch_alter_table('discount_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_codes_expiry'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_discount_codes_code_idx'), [sa.literal_column('upper(code::text)')], unique=False)
        batch_op.create_index(batch_op.f('ix_discount_codes_active'), ['is_active'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('audit_logs_status_check'), "status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying, 'error'::character varying]::text[])")

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('assignments_status_check'), "status::text = ANY (ARRAY['assigned'::character varying, 'in-progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])")

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('appointments_status_check'), "status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in-progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'rescheduled'::character varying, 'overdue'::character varying]::text[])")
        batch_op.drop_index(batch_op.f('ix_appointments_reminder_sent'))
        batch_op.drop_index(batch_op.f('ix_appointments_overdue_notified'))
        batch_op.create_index(batch_op.f('ix_appointments_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_user_date_idx'), ['user_id', sa.literal_column('appointment_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status_idx'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status_date_idx'), ['status', sa.literal_column('appointment_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_date_idx'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
